name: Build and Push Stock Prediction Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
<<<<<<< HEAD
#jkj
=======
  id-token: write

>>>>>>> 6a6ac8ce1531f9badbc842c93c40816ebe9f7523
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

<<<<<<< HEAD
=======
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

>>>>>>> 6a6ac8ce1531f9badbc842c93c40816ebe9f7523
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/stock-prediction:latest
<<<<<<< HEAD
=======
          file: ./Dockerfile
>>>>>>> 6a6ac8ce1531f9badbc842c93c40816ebe9f7523
